files:
  - source: /messages/en-US/primary.json
    dest: /mobile/primary.json
    translation: /messages/%locale%/primary.json

  - source: /messages/en-US/secondary.json
    dest: /mobile/secondary.json
    translation: /messages/%locale%/secondary.json
