// @ts-check

/**
 * @type {import("@mapeo/schema").Observation[]}
 */
export const mockObservations = [
  {
    schemaName: 'observation',
    refs: [
      {
        id: 'fC68D4fB881DaB23Ae6372b2Basd2fF3a2',
      },
      {
        id: '198Ac0C19ddAFaBbA72aba9d0D5A2b5D052',
      },
      {
        id: '7a39dcfe44FfC5871f7CasdE8F9aE2C46Cc',
      },
      {
        id: '30Bec1fbAc43f28e7EdaasdBdb9aCc8d0b6',
      },
      {
        id: 'EEC4BBeefb3ea80De05cAasd455ddbD2201',
      },
    ],
    attachments: [],
    tags: {
      categoryId: '9',
      notes: 'this is a test observation',
    },
    metadata: {},
    lat: -67.8898,
    lon: 98.04,
    links: [],
    docId: '1',
    createdAt: '1908-11-18T19:20:24.0Z',
    createdBy: '2DAa8CB21asdf8CA2002669fBCf7d2dB2Db9',
    updatedAt: '',
    versionId: '',
    deleted: false,
  },
  {
    schemaName: 'observation',
    refs: [
      {
        id: 'fC68D4fB881DaB23Ae6372b2B52fF3a2',
      },
      {
        id: '198Ac0C19ddAFaBbA729d0D5A2b5D052',
      },
      {
        id: '7a39dcfe44FfC5871f7CE8F9aE2C46Cc',
      },
      {
        id: '30Bec1fbAc43f28e7EdaBdb9aCc8d0b6',
      },
      {
        id: 'EEC4BBeefb3ea80De05cA455ddbD2201',
      },
    ],
    attachments: [],
    tags: {
      categoryId: '8',
      notes: 'Another Observation',
    },
    metadata: {},
    lat: 49.76,
    lon: 123.1,
    links: [],
    docId: '2',
    createdAt: '1908-11-18T19:20:24.0Z',
    createdBy: '2DAa8asCB218CA2002669fBCf7d2dB2Db9',
    updatedAt: '',
    versionId: '',
    deleted: false,
  },
  {
    schemaName: 'observation',
    refs: [
      {
        id: 'fC68D4afB881DaB23Ae6372b2B52fF3a2',
      },
      {
        id: '198Ac0asgC19ddAFaBbA729d0D5A2b5D052',
      },
      {
        id: '7a39dcfage44FfC5871f7CE8F9aE2C46Cc',
      },
      {
        id: '30Bec1fbeaeAc43f28e7EdaBdb9aCc8d0b6',
      },
      {
        id: 'EEC4BBeeegafb3ea80De05cA455ddbD2201',
      },
    ],
    attachments: [
      {
        driveDiscoveryId: 'fb3ea80De05cA455d',
        hash: '1fbeaeAc43f28e7EdaBdb9aCc8d0b6',
        name: 'Church',
        type: 'photo',
      },
    ],
    tags: {
      categoryId: '2',
      notes: 'Observation',
    },
    metadata: {},
    lat: -77.8898,
    lon: 98.0181,
    links: [],
    docId: '3',
    createdAt: '1899-01-17T03:34:04.0Z',
    createdBy: '2DAa8CB2a18CA2002669fBCf7d2dB2Db9',
    updatedAt: '',
    versionId: '',
    deleted: false,
  },
];

/**
 * @type {(import("@mapeo/schema").Preset)[]}
 */
export const MockPreset = [
  {
    schemaName: 'preset',
    name: 'threat',
    createdAt: '1899-01-17T03:34:04.0Z',
    createdBy: '',
    docId: '1',
    versionId: '',
    updatedAt: '1899-01-17T03:34:04.0Z',
    addTags: {},
    geometry: ['point'],
    tags: {},
    removeTags: {},
    fieldIds: [],
    terms: [],
    links: [],
    deleted: false,
  },
  {
    schemaName: 'preset',
    name: 'fountain',
    createdAt: '1899-01-17T03:34:05.0Z',
    createdBy: '',
    docId: '2',
    versionId: '',
    updatedAt: '1899-01-17T03:34:05.0Z',
    addTags: {},
    geometry: ['point'],
    tags: {},
    removeTags: {},
    fieldIds: [],
    terms: [],
    links: [],
    deleted: false,
  },
  {
    schemaName: 'preset',
    name: 'lake',
    createdAt: '1899-01-17T03:34:06.0Z',
    createdBy: '',
    docId: '3',
    versionId: '',
    updatedAt: '1899-01-17T03:34:06.0Z',
    addTags: {},
    geometry: ['point'],
    tags: {},
    removeTags: {},
    fieldIds: [],
    terms: [],
    links: [],
    deleted: false,
  },
  {
    schemaName: 'preset',
    name: 'fishing spot',
    createdAt: '1899-01-17T03:34:08.0Z',
    createdBy: '',
    docId: '4',
    versionId: '',
    updatedAt: '1899-01-17T03:34:08.0Z',
    addTags: {},
    geometry: ['point'],
    tags: {},
    removeTags: {},
    fieldIds: [],
    terms: [],
    links: [],
    deleted: false,
  },
  {
    schemaName: 'preset',
    name: 'cultural site',
    createdAt: '1899-01-17T03:32:04.0Z',
    createdBy: '',
    docId: '5',
    versionId: '',
    updatedAt: '1899-01-17T03:32:04.0Z',
    addTags: {},
    geometry: ['point'],
    tags: {},
    removeTags: {},
    fieldIds: ['24'],
    terms: [],
    links: [],
    deleted: false,
  },
  {
    schemaName: 'preset',
    name: 'House',
    createdAt: '1899-01-17T03:30:04.0Z',
    createdBy: '',
    docId: '6',
    versionId: '',
    updatedAt: '1899-01-17T03:30:04.0Z',
    addTags: {},
    geometry: ['point'],
    tags: {},
    removeTags: {},
    fieldIds: ['21'],
    terms: [],
    links: [],
    deleted: false,
  },
  {
    schemaName: 'preset',
    name: 'Balcony',
    createdAt: '1899-01-17T03:31:04.0Z',
    createdBy: '',
    docId: '7',
    versionId: '',
    updatedAt: '1899-01-17T03:31:04.0Z',
    addTags: {},
    geometry: ['point'],
    tags: {},
    removeTags: {},
    fieldIds: ['21', '22'],
    terms: [],
    links: [],
    deleted: false,
  },
  {
    schemaName: 'preset',
    name: 'Basillica',
    createdAt: '1899-01-17T03:34:09.0Z',
    createdBy: '',
    docId: '8',
    versionId: '',
    updatedAt: '1899-01-17T03:34:09.0Z',
    addTags: {},
    geometry: ['point'],
    tags: {},
    removeTags: {},
    fieldIds: [],
    terms: [],
    links: [],
    deleted: false,
  },
  {
    schemaName: 'preset',
    name: 'Satanic Temple',
    createdAt: '1899-01-17T03:39:04.0Z',
    createdBy: '',
    docId: '9',
    versionId: '',
    updatedAt: '1899-01-17T03:39:04.0Z',
    addTags: {},
    geometry: ['point'],
    tags: {},
    removeTags: {},
    fieldIds: ['21', '22', '23', '24'],
    terms: [],
    links: [],
    deleted: false,
  },
];

/**
 * @type {(import("@mapeo/schema").FieldValue & {docId:string})[]}
 */
export const mockFields = [
  {
    tagKey: '1',
    type: 'text',
    label: 'What is happening',
    appearance: 'singleline',
    snakeCase: false,
    placeholder: 'things happening',
    helperText: 'describe the situation',
    schemaName: 'field',
    docId: '21',
  },
  {
    tagKey: '2',
    type: 'text',
    label: 'Multiline - What is happening',
    appearance: 'multiline',
    snakeCase: false,
    placeholder: 'multiline placeholder',
    helperText: 'describe the situation for the multilin',
    schemaName: 'field',
    docId: '22',
  },
  {
    tagKey: '3',
    type: 'selectOne',
    label: 'singleSelect',
    options: [
      {label: 'first single select', value: 'first'},
      {label: 'second single select', value: 'second'},
      {label: 'third single select', value: 'third'},
    ],
    snakeCase: false,
    placeholder: 'you should not be able to see this',
    helperText: 'choose a singleselect',
    schemaName: 'field',
    docId: '23',
  },
  {
    tagKey: '4',
    type: 'selectMultiple',
    label: 'Multi Select',
    options: [
      {label: 'first multi select', value: 'first'},
      {label: 'second multi select', value: 'second'},
      {label: 'third multi select', value: 'third'},
    ],
    helperText: 'This is a multi-select',
    schemaName: 'field',
    docId: '24',
  },
];
