# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
'require.resolve(
  "react-native/scripts/react_native_pods.rb",
  {paths: [process.argv[1]]},
  )', __dir__]).strip
  
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

# https://github.com/rnmapbox/maps/blob/v10.0/ios/install.md#mapbox-maps-sdk-v10
$RNMapboxMapsImpl = 'mapbox'

target 'CoMapeo' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'CoMapeoTests' do
    inherit! :complete
    # Pods for testing
  end

  pre_install do |installer|
    # https://github.com/rnmapbox/maps/blob/v10.0/ios/install.md
    $RNMapboxMaps.pre_install(installer)
  end

  post_install do |installer|
    # https://github.com/rnmapbox/maps/blob/v10.0/ios/install.md
    $RNMapboxMaps.pre_install(installer)
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
