// @ts-check

import {FieldValue, Observation, Preset, PresetValue} from '@mapeo/schema';

export const mockObservations: Observation[] = [
  {
    schemaName: 'observation',
    refs: [
      {
        id: 'fC68D4fB881DaB23Ae6372b2Basd2fF3a2',
      },
      {
        id: '198Ac0C19ddAFaBbA72aba9d0D5A2b5D052',
      },
      {
        id: '7a39dcfe44FfC5871f7CasdE8F9aE2C46Cc',
      },
      {
        id: '30Bec1fbAc43f28e7EdaasdBdb9aCc8d0b6',
      },
      {
        id: 'EEC4BBeefb3ea80De05cAasd455ddbD2201',
      },
    ],
    attachments: [],
    tags: {
      categoryId: '9',
      notes: 'this is a test observation',
    },
    metadata: {},
    lat: -67.8898,
    lon: 98.04,
    links: [],
    docId: '1',
    createdAt: '1908-11-18T19:20:24.0Z',
    createdBy: '2DAa8CB21asdf8CA2002669fBCf7d2dB2Db9',
    updatedAt: '',
    versionId: '',
    deleted: false,
  },
  {
    schemaName: 'observation',
    refs: [
      {
        id: 'fC68D4fB881DaB23Ae6372b2B52fF3a2',
      },
      {
        id: '198Ac0C19ddAFaBbA729d0D5A2b5D052',
      },
      {
        id: '7a39dcfe44FfC5871f7CE8F9aE2C46Cc',
      },
      {
        id: '30Bec1fbAc43f28e7EdaBdb9aCc8d0b6',
      },
      {
        id: 'EEC4BBeefb3ea80De05cA455ddbD2201',
      },
    ],
    attachments: [],
    tags: {
      categoryId: '8',
      notes: 'Another Observation',
    },
    metadata: {},
    lat: 49.76,
    lon: 123.1,
    links: [],
    docId: '2',
    createdAt: '1908-11-18T19:20:24.0Z',
    createdBy: '2DAa8asCB218CA2002669fBCf7d2dB2Db9',
    updatedAt: '',
    versionId: '',
    deleted: false,
  },
  {
    schemaName: 'observation',
    refs: [
      {
        id: 'fC68D4afB881DaB23Ae6372b2B52fF3a2',
      },
      {
        id: '198Ac0asgC19ddAFaBbA729d0D5A2b5D052',
      },
      {
        id: '7a39dcfage44FfC5871f7CE8F9aE2C46Cc',
      },
      {
        id: '30Bec1fbeaeAc43f28e7EdaBdb9aCc8d0b6',
      },
      {
        id: 'EEC4BBeeegafb3ea80De05cA455ddbD2201',
      },
    ],
    attachments: [
      {
        driveDiscoveryId: 'fb3ea80De05cA455d',
        hash: '1fbeaeAc43f28e7EdaBdb9aCc8d0b6',
        name: 'Church',
        type: 'photo',
      },
    ],
    tags: {
      categoryId: '2',
      notes: 'Observation',
    },
    metadata: {},
    lat: -77.8898,
    lon: 98.0181,
    links: [],
    docId: '3',
    createdAt: '1899-01-17T03:34:04.0Z',
    createdBy: '2DAa8CB2a18CA2002669fBCf7d2dB2Db9',
    updatedAt: '',
    versionId: '',
    deleted: false,
  },
];

export const MockPreset: PresetValue[] = [
  {
    schemaName: 'preset',
    name: 'Animal',
    geometry: ['point', 'area'],
    tags: {type: 'animal'},
    addTags: {},
    removeTags: {},
    fieldIds: ['abc123'],
    iconId: 'animal',
    terms: [],
  },
  {
    schemaName: 'preset',
    name: 'Boundary',
    geometry: ['point', 'line'],
    tags: {boundary: 'indigenous', type: 'boundary'},
    addTags: {},
    removeTags: {},
    fieldIds: [],
    iconId: 'boundary',
    terms: ['border', 'frontier'],
  },
  {
    schemaName: 'preset',
    name: 'Airstrip',
    geometry: ['point', 'area'],
    tags: {aeroway: 'airstrip', type: 'aeroway'},
    addTags: {},
    removeTags: {},
    fieldIds: ['def678'],
    iconId: 'airstrip',
    terms: ['airfield', 'airport', 'landing'],
  },
  {
    schemaName: 'preset',
    name: 'Building',
    geometry: ['point'],
    tags: {type: 'building'},
    addTags: {},
    removeTags: {},
    fieldIds: ['stu901'],
    iconId: 'building',
    terms: ['medical', 'school'],
  },
  {
    schemaName: 'preset',
    name: 'Camp',
    geometry: ['point'],
    tags: {type: 'camp'},
    addTags: {},
    removeTags: {},
    fieldIds: ['pqr678'],
    iconId: 'camp',
    terms: ['campsite', 'camping', 'hunting'],
  },
  {
    schemaName: 'preset',
    name: 'Cave',
    geometry: ['point'],
    tags: {natural: 'cave_entrance', type: 'natural'},
    addTags: {},
    removeTags: {},
    fieldIds: ['jkl012'],
    iconId: 'cave',
    terms: [],
  },
  {
    schemaName: 'preset',
    name: 'Clay',
    geometry: ['point'],
    tags: {craft: 'clay', type: 'craft'},
    addTags: {},
    removeTags: {},
    fieldIds: [],
    iconId: 'clay',
    terms: [],
  },
  {
    schemaName: 'preset',
    name: 'Community',
    geometry: ['point', 'area'],
    tags: {place: 'village'},
    addTags: {},
    removeTags: {},
    fieldIds: ['jkl012'],
    iconId: 'community',
    terms: ['village'],
  },
  {
    schemaName: 'preset',
    name: 'Hills',
    geometry: ['point', 'area'],
    tags: {natural: 'peak', type: 'natural'},
    addTags: {},
    removeTags: {},
    fieldIds: ['jkl012'],
    iconId: 'hills',
    terms: ['mountains'],
  },
  {
    schemaName: 'preset',
    name: 'House',
    geometry: ['point'],
    tags: {building: 'residential'},
    addTags: {},
    removeTags: {},
    fieldIds: ['pqr678'],
    iconId: 'house',
    terms: ['house', 'home'],
  },
  {
    schemaName: 'preset',
    name: 'Gathering Site',
    geometry: ['point', 'area'],
    tags: {activity: 'gathering', type: 'activity'},
    addTags: {},
    removeTags: {},
    fieldIds: ['ghi789'],
    iconId: 'gathering',
    terms: ['collection'],
  },
  {
    schemaName: 'preset',
    name: 'Hunting Site',
    geometry: ['point', 'area'],
    tags: {activity: 'hunting', type: 'activity'},
    addTags: {},
    removeTags: {},
    fieldIds: ['abc123'],
    iconId: 'hunting',
    terms: [],
  },
  {
    schemaName: 'preset',
    name: 'Palm',
    geometry: ['point', 'area'],
    tags: {natural: 'tree', tree: 'palm', type: 'natural'},
    addTags: {},
    removeTags: {},
    fieldIds: ['stu901'],
    iconId: 'palm',
    terms: [],
  },
  {
    schemaName: 'preset',
    name: 'Path',
    geometry: ['point', 'line'],
    tags: {highway: 'footway', type: 'highway'},
    addTags: {},
    removeTags: {},
    fieldIds: ['def678'],
    iconId: 'path',
    terms: [''],
  },
  {
    schemaName: 'preset',
    name: 'Plant',
    geometry: ['point', 'area'],
    tags: {natural: 'plant', type: 'natural'},
    addTags: {},
    removeTags: {},
    fieldIds: ['yz012'],
    iconId: 'plant',
    terms: [],
  },
  {
    schemaName: 'preset',
    name: 'New point',
    geometry: ['point'],
    tags: {nuevo: 'yes'},
    addTags: {},
    removeTags: {},
    fieldIds: [],
    iconId: 'estrella',
    terms: [],
  },
  {
    schemaName: 'preset',
    name: 'River',
    geometry: ['point', 'line'],
    tags: {type: 'waterway', waterway: 'river'},
    addTags: {},
    removeTags: {},
    fieldIds: ['vwx234'],
    iconId: 'river',
    terms: [],
  },
  {
    schemaName: 'preset',
    name: 'Lake',
    geometry: ['point', 'area'],
    tags: {natural: 'water', type: 'natural', water: 'lake'},
    addTags: {},
    removeTags: {},
    fieldIds: ['vwx234'],
    iconId: 'lake',
    terms: [],
  },
  {
    schemaName: 'preset',
    name: 'Salt lick',
    geometry: ['point'],
    tags: {natural: 'salt-lick', type: 'natural'},
    addTags: {},
    removeTags: {},
    fieldIds: ['abc123'],
    iconId: 'salt-lick',
    terms: [],
  },
  {
    schemaName: 'preset',
    name: 'Special site',
    geometry: ['point', 'area'],
    tags: {cultural: 'cultural-site', type: 'cultural'},
    addTags: {},
    removeTags: {},
    fieldIds: ['jkl012'],
    iconId: 'special-site',
    terms: ['story', 'sacred', 'historical', 'history'],
  },
  {
    schemaName: 'preset',
    name: 'Stream',
    geometry: ['point', 'line'],
    tags: {type: 'waterway', waterway: 'stream'},
    addTags: {},
    removeTags: {},
    fieldIds: ['vwx234'],
    iconId: 'stream',
    terms: [],
  },
  {
    schemaName: 'preset',
    name: 'Swidden',
    geometry: ['point', 'area'],
    tags: {landuse: 'farmland', type: 'landuse'},
    addTags: {},
    removeTags: {},
    fieldIds: ['pqr678'],
    iconId: 'swidden',
    terms: ['farm', 'garden', 'plot', 'allotment', 'paddy', 'cultivation'],
  },
  {
    schemaName: 'preset',
    name: 'Fishing Site',
    geometry: ['point', 'area'],
    tags: {activity: 'fishing', type: 'activity'},
    addTags: {},
    removeTags: {},
    fieldIds: ['jkl012'],
    iconId: 'fishing',
    terms: ['fish'],
  },
  {
    schemaName: 'preset',
    name: 'Threat',
    geometry: ['point', 'area', 'line'],
    tags: {impact: 'threat', type: 'impact'},
    addTags: {},
    removeTags: {},
    fieldIds: [],
    iconId: 'threat',
    terms: ['danger', 'illegal', 'monitoring'],
  },
  {
    schemaName: 'preset',
    name: 'Tree',
    geometry: ['point', 'area'],
    tags: {natural: 'tree', type: 'natural'},
    addTags: {},
    removeTags: {},
    fieldIds: ['abc345'],
    iconId: 'tree',
    terms: [],
  },
  {
    schemaName: 'preset',
    name: 'Waterfall',
    geometry: ['point'],
    tags: {type: 'waterway', waterway: 'waterfall'},
    addTags: {},
    removeTags: {},
    fieldIds: ['vwx234'],
    iconId: 'waterfall',
    terms: ['cascade'],
  },
];

export const mockFields: (FieldValue & {docId: string})[] = [
  {
    schemaName: 'field',
    tagKey: 'animal-type',
    type: 'text',
    label: 'Animal type',
    placeholder: 'What kind of animal?',
    docId: 'abc123',
  },
  {
    schemaName: 'field',
    tagKey: 'building-type',
    type: 'selectOne',
    label: 'Building type',
    options: [
      {label: 'School', value: 'School'},
      {label: 'Hospital', value: 'Hospital'},
      {label: 'Homestead', value: 'Homestead'},
      {label: 'Church', value: 'Church'},
      {label: 'Shop', value: 'Shop'},
      {label: 'Other', value: 'Other'},
    ],
    placeholder: 'School/hospital/etc',
    docId: 'def456',
  },
  {
    schemaName: 'field',
    tagKey: 'items-gathered',
    type: 'text',
    label: 'What is gathered here?',
    placeholder: 'e.g. firewood / medicine etc.',
    docId: 'ghi789',
  },
  {
    schemaName: 'field',
    tagKey: 'name',
    type: 'text',
    label: 'Name',
    universal: true,
    placeholder: 'Common name of this place',
    docId: 'jkl012',
  },
  {
    schemaName: 'field',
    tagKey: 'note',
    type: 'text',
    label: 'Note',
    placeholder: 'Stories or notes about this place',
    docId: 'mno345',
  },
  {
    schemaName: 'field',
    tagKey: 'owner',
    type: 'text',
    label: 'Owner',
    placeholder: 'Owner or user of the place',
    docId: 'pqr678',
  },
  {
    schemaName: 'field',
    tagKey: 'palm-species',
    type: 'text',
    label: 'Palm species',
    placeholder: 'What kind of palm?',
    docId: 'stu901',
  },
  {
    schemaName: 'field',
    tagKey: 'source',
    type: 'text',
    label: 'Source',
    placeholder: 'Source of the data',
    docId: 'vwx234',
  },
  {
    schemaName: 'field',
    tagKey: 'plant-species',
    type: 'text',
    label: 'Plant species',
    placeholder: 'What kind of plant?',
    docId: 'yz012',
  },
  {
    schemaName: 'field',
    tagKey: 'tree-species',
    type: 'text',
    label: 'Tree species',
    placeholder: 'What kind of tree?',
    docId: 'abc345',
  },
  {
    schemaName: 'field',
    tagKey: 'type',
    type: 'text',
    label: 'What kind of path?',
    placeholder: 'What is this path used for?',
    docId: 'def678',
  },
];
