import {describe} from 'mocha';

describe('CoMapeo E2E Flow', function () {
  require('./onboarding/data-privacy.test');
  require('./onboarding/privacy-policy.test');
  require('./onboarding/device-naming.test');
  require('./project/edit-device-name.test');
  require('./project/own-project-headers.test');
  require('./main/side-drawer-menu-no-proj.test');
  require('./project/project-settings-no-proj.test');
  require('./observations/create-observation.test');
  require('./tracks/start-track.test');
  require('./project/invite-collaborators.test');
  require('./project/rename-project-from-drawer.test');
  // require('./project/unjoin-project.test');
  require('./main/side-drawer-menu-proj.test');
  require('./project/project-settings-proj.test');
  require('./main/map.test');
  require('./observations/add-details.test');
  require('./observations/view-observations.test');
  require('./observations/edit-observation.test');
  require('./observations/delete-observation.test');
  require('./tracks/save-track.test');
  require('./tracks/view-edit-track.test');
  require('./audio/audio-recording.test');
  require('./audio/audio-playback-delete.test');
  require('./audio/audio-add-additional.test');
  require('./settings/coordinates.test');
  require('./settings/language.test');
  require('./settings/about-comapeo.test');
  require('./passcode/obscure-passcode-visibility.test');
  require('./passcode/set-passcode.test');
  require('./passcode/obscure-mode.test');
  require('./passcode/check-passcode-requirements.test');
  require('./passcode/post-passcode-setup.test');
  require('./main/restart-navigation.test');
});
