name: Build Release

on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    outputs:
      eas_build_url: ${{ steps.build.outputs.eas_build_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Set up Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build on EAS
        id: build
        env:
          EAS_PROJECT_URL: ${{ vars.EAS_PROJECT_URL }}
        run: |
          build_id=$( eas build --platform android --profile production --json --non-interactive --no-wait | jq '.[0].id' --raw-output )
          if [ -z "$build_id" ]; then
            echo "Unable to get build ID"
            exit 1
          fi
          echo "Build ID: $build_id"
          eas_build_url="$EAS_PROJECT_URL/builds/$build_id"
          echo "eas_build_url=$eas_build_url" >> $GITHUB_OUTPUT

  comment:
    name: Comment
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}

      - name: Comment on PR
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          COMMENT_BODY: |
            :rocket: Release build based on ${{ github.event.pull_request.merge_commit_sha }}: ${{ needs.build.outputs.eas_build_url }}

        run: |
          gh pr comment $PR_NUMBER --body "$COMMENT_BODY" --repo "$GITHUB_REPOSITORY"

  tag:
    name: Create release tag
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - run: npm install --no-save semver
        shell: bash

      - name: Extract release versions
        id: version
        run: |
          release_version_short=$(node -e "const {version} = require('./package.json'); const semver = require('semver'); const parsed = semver.parse(version); console.log(parsed.minor + '.' + parsed.patch);")
          echo "release_version_short=$release_version_short" >> $GITHUB_OUTPUT

      - name: Tag release
        run: |
          git config --global user.name 'awana-release-bot[bot]'
          git config --global user.email '${{ vars.RELEASE_BOT_USER_ID }}+awana-release-bot[bot]@users.noreply.github.com'
          git tag v${{ steps.version.outputs.release_version_short }}
          git push origin v${{ steps.version.outputs.release_version_short }}
