name: E2E CI

on:
  push:
    branches:
      - chore/e2e-ci

jobs:
  e2e-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
          cache: 'npm'

      - name: Ensure npm is at v10.x
        run: npm install -g npm@10

      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Authenticate with Expo
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      - name: Set Gradle properties
        run: |
          echo "org.gradle.jvmargs=-Xmx4096m" >> gradle.properties

      - name: Build Android app locally with EAS
        env:
          SENTRY_DISABLE_AUTO_UPLOAD: true
        run: eas build --platform android --profile test --local

      - name: Find APK
        id: find_apk
        run: |
          APK_PATH=$(find . -type f -name "*.apk" | head -n 1)
          echo "::set-output name=apk_path::$APK_PATH"

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up Android Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          ndk: 25.1.8937393
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          script: |
            adb install ${{ steps.find_apk.outputs.apk_path }}
            curl -Ls "https://get.maestro.mobile.dev" | bash
            export PATH="$PATH:$HOME/.maestro/bin"
            maestro test e2e

      - name: Wait for emulator to start
        run: |
          adb wait-for-device
          for i in {1..30}; do
            adb shell getprop sys.boot_completed && break || sleep 10
          done

      - name: Unlock screen
        run: adb shell input keyevent 82
